export enum ApiEndpoints {
  Login = "users/login",
  VerifyUser = "users/verify",
  forgetPassword = "users/forgetPassword",
  verifyResetPasswordCode = "users/verifyResetPasswordCode",
  resetPassword = "users/resetPassword",
  resendVerificationCode = "users/resendVerificationCode",
  register = "users/register",
  threadsListList = "threadsList",
  getUserMailBoxes = "inbox/mailboxes",
  threadList = "inbox",
  userDetailsPath = "users/getUserData",
  contactsList = "contacts",
  compose = "inbox/send",
  threadMessages = "inbox/chat",
  getAttachmentsLink = "attachments/link",
}
