export enum ApiEndpoints {
  Login = "users/login",
  VerifyUser = "users/verify",
  forgetPassword = "users/forgetPassword",
  verifyResetPasswordCode = "users/verifyResetPasswordCode",
  resetPassword = "users/resetPassword",
  resendVerificationCode = "users/resendVerificationCode",
  register = "users/register",
  threadsListList = "threadsList",
  getUserMailBoxes = "inbox/mailboxes",
  threadList = "inbox",
  userDetailsPath = "users/getUserData",
  contactsList = "contacts",
  compose = "inbox/send",
  threadMessages = "inbox/chat",
  getAttachmentsLink = "attachments/link",
  createAttachment = "attachments",
  editMessage = "messages",
  bookmarks = "inbox/threads/bookmark",
  deleteForAll = "messages/forAll",
  deleteForMe = "messages/forMe",
  Emoji = "reactions",
  Devices = "devices",
  Notifications = "notifications",
}
