export enum Apis {
  Login = "users/login",
  VerifyUser = "users/verify",
  forgetPassword = "users/forgetPassword",
  verifyResetPasswordCode = "users/verifyResetPasswordCode",
  resetPassword = "users/resetPassword",
  resendVerificationCode = "users/resendVerificationCode",
  register = "users/register",
  threadsListList = "threadsList",
  getUserMailBoxes = "mailboxes/getAllUserMailboxes",
  threadList = "threads/fetchThreads",
  userDetailsPath = "users/getUserData",
  contactsList = "contacts/get",
  compose = "mail/compose",
}
